

UNIQUE_NAMES = ['Alice', 'Bob', 'Clara', 'David', 'Emily', 'Frank', 'Grace', 'Henry', 'Irene', 'Jack', 'Karen', 'Leo', 'Maria', 'Nathan', 'Olivia', 'Paul', 'Quinn', 'Ryan', 'Sarah', 'Thomas', 'Ursula', 'Victor', 'Wendy', 'Xavier', 'Yvonne', 'Zachary', 'Andrea', 'Ben', 'Cindy', 'Derek', 'Erin', 'Felix', 'Gina', 'Harold', 'Ingrid', 'Jake', 'Kelly', 'Lance', 'Melissa', 'Noah', 'Patricia', 'Quentin', 'Rachel', 'Sam', 'Tina', 'Vince', 'Wendy', 'Zach', 'Abigail', 'Blake', 'Chloe', 'Daniel', 'Emma', 'George', 'Helen', 'Isaac', 'Julia', 'Kevin', 'Lisa', 'Mason', 'Nicole', 'Owen', 'Penelope', 'Ray', 'Stella', 'Tony', 'Vanessa', 'Wyatt', 'Zoey', 'Amanda', 'Brad', 'Courtney', 'Dylan', 'Elise', 'Felix', 'Grace', 'Hayden', 'Ivy', 'Jake', 'Kate', 'Liam', 'Megan', 'Oscar', 'Quinn', 'Ruby', 'Seth', 'Tara', 'Victor', 'Wanda', 'Xavier', 'Yasmine', 'Zachary', 'Amy', 'Ben', 'Christina', 'Derek', 'Emily', 'Frank', 'Giselle', 'Henry', 'Isabel', 'Justin', 'Karen', 'Leo', 'Morgan', 'Nora', 'Peter', 'Quinn', 'Rachel', 'Sean', 'Tracy', 'Vaughn', 'Willow', 'Zane', 'Andrea', 'Brian', 'Colleen', 'Damian', 'Erin', 'Fiona', 'Gavin', 'Heather', 'Ian', 'Jessica', 'Kyle', 'Laura', 'Mason', 'Natalie', 'Oliver', 'Paige', 'Quincy', 'Rose', 'Scott', 'Tiffany', 'Victor', 'Wendy', 'Xavier', 'Yvonne', 'Zachary', 'Alexa', 'Brad', 'Clara', 'Derek', 'Emma', 'Felix', 'Grace', 'Henry', 'Ingrid', 'Jake', 'Karen', 'Leo', 'Maria', 'Nathan', 'Olivia', 'Paul', 'Quinn', 'Ryan', 'Sarah', 'Thomas', 'Ursula', 'Victor', 'Wendy', 'Xavier', 'Yvonne', 'Zachary', 'Andrea', 'Ben', 'Cindy', 'Derek', 'Erin', 'Felix', 'Gina', 'Harold', 'Ingrid', 'Jake', 'Kelly', 'Lance', 'Melissa', 'Noah', 'Patricia', 'Quentin', 'Rachel', 'Sam', 'Tina', 'Vince', 'Wendy', 'Zach', 'Abigail', 'Blake', 'Chloe', 'Daniel', 'Emma', 'George', 'Helen', 'Isaac', 'Julia', 'Kevin', 'Lisa', 'Mason', 'Nicole', 'Owen', 'Penelope', 'Ray', 'Stella', 'Tony', 'Vanessa', 'Wyatt', 'Zoey', 'Amanda', 'Brad', 'Courtney', 'Dylan', 'Elise', 'Felix', 'Grace', 'Hayden', 'Ivy', 'Jake', 'Kate', 'Liam', 'Megan', 'Oscar', 'Quinn', 'Ruby', 'Seth', 'Tara', 'Victor', 'Wanda', 'Xavier', 'Yasmine', 'Zachary', 'Amy', 'Ben', 'Christina', 'Derek', 'Emily', 'Frank', 'Giselle', 'Henry', 'Isabel', 'Justin', 'Karen', 'Leo', 'Morgan', 'Nora', 'Peter', 'Quinn', 'Rachel', 'Sean', 'Tracy', 'Vaughn', 'Willow', 'Zane', 'Andrea', 'Brian', 'Colleen', 'Damian', 'Erin', 'Fiona', 'Gavin', 'Heather', 'Ian', 'Jessica', 'Kyle', 'Laura', 'Mason', 'Natalie', 'Oliver', 'Paige', 'Quincy', 'Rose', 'Scott', 'Tiffany', 'Victor', 'Wendy', 'Xavier', 'Yvonne', 'Zachary', 'Alexa', 'Brad', 'Luna', 'Orion', 'Seraphina', 'Dante', 'Aurora', 'Magnus', 'Freya', 'Atlas', 'Selene', 'Maximus', 'Isabella', 'Apollo', 'Astrid', 'Titan', 'Aria', 'Phoenix', 'Lyra', 'Thaddeus', 'Nova', 'Orion', 'Celeste', 'Zephyr', 'Astrid', 'Apollo', 'Cassius', 'Calliope', 'Caelum', 'Elara', 'Galadriel', 'Oberon', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Valkyrie', 'Apollo', 'Cassius', 'Calliope', 'Caelum', 'Elara', 'Galadriel', 'Oberon', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Valkyrie', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Apollo', 'Cassius', 'Calliope', 'Caelum', 'Elara', 'Galadriel', 'Oberon', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Valkyrie', 'Apollo', 'Cassius', 'Calliope', 'Caelum', 'Elara', 'Galadriel', 'Oberon', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander', 'Apollo', 'Cassius', 'Calliope', 'Caelum', 'Elara', 'Galadriel', 'Oberon', 'Niamh', 'Azriel', 'Elowen', 'Griffin', 'Valkyrie', 'Kieran', 'Nereus', 'Sylas', 'Thalia', 'Aether', 'Calypso', 'Leander']
UNIQUE_SURNAMES = ['Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson', 'Clark', 'Rodriguez', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young', 'Hernandez', 'King', 'Wright', 'Lopez', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray', 'Ramirez', 'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood', 'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzalez', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes', 'Myers', 'Ford', 'Hamilton', 'Graham', 'Sullivan', 'Wallace', 'Woods', 'Cole', 'West', 'Jordan', 'Owens', 'Reynolds', 'Fisher', 'Ellis', 'Harrison', 'Gibson', 'Mcdonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray', 'Freeman', 'Wells', 'Webb', 'Simpson', 'Stevens', 'Tucker', 'Porter', 'Hunter', 'Hicks', 'Crawford', 'Henry', 'Boyd', 'Mason', 'Morales', 'Kennedy', 'Warren', 'Dixon', 'Ramos', 'Reyes', 'Burns', 'Gordon', 'Shaw', 'Holmes', 'Rice', 'Robertson', 'Hunt', 'Black', 'Daniels', 'Palmer', 'Mills', 'Nichols', 'Grant', 'Knight', 'Ferguson', 'Rose', 'Stone', 'Hawkins', 'Dunn', 'Perkins', 'Hudson', 'Spencer', 'Gardner', 'Stephens', 'Payne', 'Pierce', 'Berry', 'Matthews', 'Arnold', 'Wagner', 'Willis', 'Ray', 'Watkins', 'Olson', 'Carroll', 'Duncan', 'Snyder', 'Hart', 'Cunningham', 'Bradley', 'Lane', 'Andrews', 'Ruiz', 'Harper', 'Fox', 'Riley', 'Armstrong', 'Carpenter', 'Weaver', 'Greene', 'Lawrence', 'Elliott', 'Chavez', 'Sims', 'Austin', 'Peters', 'Kelley', 'Franklin', 'Lawson', 'Fields', 'Gutierrez', 'Ryan', 'Schmidt', 'Carr', 'Vasquez', 'Castillo', 'Wheeler', 'Chapman', 'Oliver', 'Montgomery', 'Richards', 'Williamson', 'Johnston', 'Banks', 'Meyer', 'Bishop', 'Mccoy', 'Howell', 'Alvarez', 'Morrison', 'Hansen', 'Fernandez', 'Garza', 'Harvey', 'Little', 'Burton', 'Stanley', 'Nguyen', 'George']
# 0: man, 1: woman
GENDER_LABELS = [0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
WORK_MANSIONS = ['Arbitrator', 'Materials Engineer', 'Software Developer', 'Videographer', 'Requirements Analyst', 'Attorney', 'Training and Development Specialist', 'Legal Researcher', 'Dancer', 'Lobbyist', 'Full-Stack Developer', 'Quality Control Specialist', 'Logistics Manager', 'Psychologist', 'Nurse Anesthetist (CRNA)', 'IT Project Manager', 'Construction Manager', 'Plumber', 'Veterinarian', 'UX Designer', 'Prosthodontist', 'Principal', 'English Language Learner (ELL) Teacher', 'Judge', 'Environmental Engineer', 'Safety Supervisor', 'Human Resources Manager', 'Social Media Manager', 'Jazz Dancer', 'Court Reporter', 'Software Engineer', 'Business and Administrative Services', 'Curriculum Developer', 'Animation Specialist', 'Oncologist', 'Singer', 'Business Intelligence Analyst', 'Sales Enablement Specialist', 'User Interface (UI) Designer', 'Receptionist', 'Game Designer', 'UI Designer', 'Dentist', 'Educational Technology Specialist', 'Chef de Cuisine', 'Surgeon', 'Environmental Science Technician', 'Defense Attorney', 'Electrician', 'Carpenter', 'Software Engineer Manager', 'Advertising Manager', 'Nurse Manager', 'Physician Assistant', 'Psychiatrist', 'Nurse Practitioner', 'Investigative Reporter', 'Healthcare Information Technology (IT) Specialist', 'Homeless Services Worker', 'Product Manager', 'Market Researcher', 'Front-End Developer', 'Musician', 'Web Designer', 'Compliance Officer', 'Customer Service Manager', 'Information Architect', 'Portfolio Manager', 'Legal Writer', 'Physical Therapist', 'Machine Learning Engineer', 'Actress', 'Web Developer', 'Biologist', 'Playwright', 'DevOps Engineer', 'Information Security Analyst', 'Instructional Designer', 'News Anchor', 'Safety Manager', 'K-12 Teacher', 'Educational Psychologist', 'Registered Nurse (RN)', 'School Administrator', 'Choreographer', 'Forensic Analyst', 'Sales Manager', 'Emergency Medical Technician (EMT)', 'Medical Billing Specialist', 'Scientific Researcher', 'Theater Director', 'Beverage Manager', 'Teacher', 'Compensation and Benefits Specialist', 'Risk Analyst', 'Aerospace Engineer', 'HVAC Technician', 'Recreational Therapist', 'Sales Trainer', 'Producer', 'Lawyer', 'Demolition Foreman', 'Mechanical Engineer', 'Elementary School Teacher', 'Environmental Scientist', 'Dean', 'Modern Dancer', 'Endodontist', 'Law Clerk', 'Industrial Engineer', 'Chemist', 'Radio Host', 'Actuary', 'Child Protective Services Worker', 'Novelist', 'Stage Manager', 'Public Relations Manager', 'Paramedic', 'Tour Guide', 'HRIS Specialist', 'Penetration Tester', 'Sales Consultant', 'Counselor', 'Musical Director', 'School Psychologist', 'Drummer', 'Heavy Equipment Operator', 'Occupational Therapist', 'Physicist', 'Sales Coach', 'Rock Musician', 'Clinical Pharmacist', 'Pharmacist', 'Cybersecurity Specialist', 'Legal Secretary', 'Business Analyst', 'Screenwriter', 'Cardiologist', 'Drug Discovery Scientist', 'Nanotechnology Engineer', 'Content Marketing Manager', 'Graphic Designer', 'General Contractor', 'Cloud Engineer', 'Electrical Engineer', 'Substance Abuse Counselor', 'Pediatric Dentist', 'Speech-Language Pathologist', 'Public Defender', 'Pianist', 'Recruiter', 'Front of House Manager', 'Composer', 'Voice Actor', 'Community Organizer', 'Business Development Manager', 'Mediator', 'Demolition Specialist', 'Security Consultant', 'Architect', 'Opera Singer', 'Content Writer', 'Certified Nurse Midwife (CNM)', 'Customer Service Representative', 'Laboratory Technician', 'Public Relations Specialist', 'Case Manager', 'Medical Assistant', 'Special Needs Teacher', 'Safety Specialist', 'Medical Researcher', 'Professor', 'Network Engineer', 'Medical Doctor', 'Marketing Manager', 'Paralegal', 'College Professor', 'Subcontractor', 'Pediatrician', 'Oral Surgeon', 'Economic Consultant', 'Legal Counsel', 'Mental Health Counselor', 'Rigger', 'Marketing Specialist', 'Special Education Teacher', 'Superintendent', 'Multimedia Specialist', 'Photographer', 'Geologist', 'Research Scientist', 'Therapist', 'Content Manager', 'Educational Researcher', 'Legal Assistant', 'Detective', 'Data Analyst', 'Clinical Researcher', 'Social Worker', 'Political Organizer', 'Financial Analyst', 'Systems Analyst', 'Magistrate', 'Lighting Designer', 'Cloud Architect', 'Environmental Compliance Officer', 'Dance Instructor', 'Sales Recruiter', 'Sculptor', 'Chemical Engineer', 'Nonprofit Manager', 'Zoologist', 'Legislative Aide', 'Pharmaceutical Chemist', 'Pastry Chef', 'Prosecutor', 'IT Help Desk Technician', 'Environmental Specialist', 'Administrative Assistant', 'Chief Information Officer (CIO)', 'Nurse Practitioner (NP)', 'Back-End Developer', 'Quality Control Manager', 'Orchestra Conductor', 'Supply Chain Manager', 'Copywriter', 'Executive Chef', 'Ballet Dancer', 'Quantitative Analyst', 'Office Manager', 'Travel Agent', 'Painter', 'Social Activist', 'Sheriff', 'Actor', 'Line Cook', 'Cybersecurity Analyst', 'Petroleum Engineer', 'Theater Performer', 'Project Manager', 'Astronomer', 'Secret Service Agent', 'Risk Manager', 'Sous Chef', 'Guitarist', 'Chief Technology Officer (CTO)', 'Engineer Technician', 'Writer', 'Animal Physiologist', 'Healthcare Administrator', 'IT Support Specialist', 'Medical Doctor (MD)', 'Paleontologist', 'Vice Principal', 'Jazz Musician', 'Illustrator', 'Police Officer', 'Chef Manager', 'Research Engineer', 'Healthcare Administrative Assistant', 'High School Teacher', 'Biomedical Engineer', 'Estimator', 'Digital Marketing Manager', 'Journalist', 'Food and Beverage Manager', 'Community Manager', 'Medical Transcriptionist', 'Stand-up Comedian', 'Operations Research Analyst', 'Border Patrol Agent', 'Civil Engineer', 'Mineralogist', 'Legal Editor', 'Restaurant Manager', 'Artist', 'Computer and Information Technology', 'Environmental Consultant', 'IT Infrastructure Specialist', 'Medical Records Clerk', 'Statistician', 'Interaction Designer', 'Early Childhood Education Teacher', 'TV Host', 'Hotel Manager', 'Animal Behaviorist', 'Information Technology (IT) Specialist', 'Certified Nurse Midwife', 'Database Administrator', 'User Experience (UX) Designer', 'Database Analyst', 'Hospitality Manager', 'Broadcast Journalist', 'Investment Analyst', 'Chief Information Security Officer (CISO)', 'Software Architect', 'Operations Manager', 'Data Scientist', 'Event Planner', 'Editor', 'Policy Analyst', 'Statistical Programmer']

NAME_MODEL_TEXT_ENCODER = "thenlper/gte-small"

CATEGORY_MANSIONS = list(set([
    'healthcare',
    'education',
    'finance',
    'technology',
    'legal',
    'arts',
    'media',
    'hospitality',
    'construction',
    'manufacturing',
    'agriculture',
    'mining',
    'government',
    'commercial',
    'residential',
    'religious',
    'industrial',
    'military',
    'transportation',
    'recreational',
    'infrastructure',
    'science',
    'cousine',
    'fashion',
    'music',
    'other'
]))

SKILLS = [
  "Non-linear Thinking",
  "Proactiveness",
  "Critical Analysis",
  "Strategic Vision",
  "Systems Thinking",
  "Innovation",
  "Visionary Leadership",
  "Resilience",
  "Emotional Intelligence",
  "Adaptability",
  "Autonomous Decision-Making",
  "Creative Problem-Solving",
  "Entrepreneurial Mindset",
  "Intuitive Decision-Making",
  "Risk-Taking",
  "Open-mindedness",
  "Inquisitiveness",
  "Continuous Learning",
  "Self-motivation",
  "Initiative",
  "Time Management",
  "Self-discipline",
  "Goal Setting",
  "Attention to Detail",
  "Effective Communication",
  "Active Listening",
  "Collaboration",
  "Conflict Resolution",
  "Negotiation",
  "Relationship Building",
  "Team Empowerment",
  "Empathy",
  "Motivational Leadership",
  "Results-Driven",
  "Decision-Making Under Uncertainty",
  "Data-Driven Decision-Making",
  "Rapid Prototyping",
  "Experimentation",
  "Systems Optimization",
  "Complexity Management",
  "Crisis Management",
  "Change Management",
  "Influence and Persuasion",
  "Cross-functional Collaboration",
  "Cultural Sensitivity",
  "Global Perspective",
  "Networking",
  "Team Building",
  "Conflict Management",
  "Decision-Making in Ambiguity",
  "Resourcefulness",
  "Digital Literacy",
  "Global Citizenship",
  "Humility",
  "Customer-Centric Thinking",
  "Conflict Resolution",
  "Systems Integration",
  "Storytelling",
  "Ethical Decision-Making",
  "Cultural Competence",
  "Change Adaptability",
  "Conflict Resolution",
  "Systems Optimization",
  "Social Intelligence",
  "Systems Thinking",
  "Problem Sensitivity",
  "Foresight",
  "Decision Quality",
  "Learning Agility",
  "Negotiation Skills",
  "Tolerance for Ambiguity",
  "Cognitive Flexibility",
  "Cross-Cultural Competence",
  "Cultural Intelligence",
  "Intrapreneurship",
  "Team Empowerment",
  "Facilitation Skills",
  "Influence and Persuasion",
  "Resource Allocation",
  "Resilient Leadership",
  "Systems Awareness",
  "Data Literacy",
  "Open to Feedback",
  "Conflict Transformation",
  "Systems Approach",
  "Future Thinking",
  "Analytical Thinking",
  "Initiative",
  "Systems Modeling",
  "Complexity Management",
  "Skeptical Inquiry",
  "Intercultural Communication",
  "Social Entrepreneurship",
  "Complexity Management",
  "Interdisciplinary Collaboration",
  "Visionary Thinking",
  "Self-reflection",
  "Curiosity",
  "Cognitive Diversity",
  "Situational Awareness"
]

CITIES_COUNTRY = [
  ("Tokyo", "Japan"),
  ("New York", "United States"),
  ("London", "United Kingdom"),
  ("Paris", "France"),
  ("Berlin", "Germany"),
  ("Beijing", "China"),
  ("Moscow", "Russia"),
  ("Istanbul", "Turkey"),
  ("Mumbai", "India"),
  ("Rio de Janeiro", "Brazil"),
  ("Sydney", "Australia"),
  ("Cairo", "Egypt"),
  ("Dubai", "United Arab Emirates"),
  ("Toronto", "Canada"),
  ("Mexico City", "Mexico"),
  ("Seoul", "South Korea"),
  ("Cape Town", "South Africa"),
  ("Rome", "Italy"),
  ("Bangkok", "Thailand"),
  ("Amsterdam", "Netherlands"),
  ("Buenos Aires", "Argentina"),
  ("Lagos", "Nigeria"),
  ("Singapore", "Singapore"),
  ("Stockholm", "Sweden"),
  ("Hong Kong", "China"),
  ("Athens", "Greece"),
  ("Dublin", "Ireland"),
  ("Oslo", "Norway"),
  ("Vienna", "Austria"),
  ("Warsaw", "Poland"),
  ("Lisbon", "Portugal"),
  ("Helsinki", "Finland"),
  ("Brussels", "Belgium"),
  ("Prague", "Czech Republic"),
  ("Kuala Lumpur", "Malaysia"),
  ("Budapest", "Hungary"),
  ("Copenhagen", "Denmark"),
  ("Zurich", "Switzerland"),
  ("Johannesburg", "South Africa"),
  ("Auckland", "New Zealand"),
  ("Seville", "Spain"),
  ("Lima", "Peru"),
  ("Vancouver", "Canada"),
  ("Osaka", "Japan"),
  ("Edinburgh", "United Kingdom"),
  ("Krakow", "Poland"),
  ("Montreal", "Canada"),
  ("Kyiv", "Ukraine"),
  ("Hamburg", "Germany"),
  ("São Paulo", "Brazil"),
  ("Delhi", "India"),
  ("Barcelona", "Spain"),
  ("Nairobi", "Kenya"),
  ("Tel Aviv", "Israel"),
  ("Munich", "Germany"),
  ("Cologne", "Germany"),
  ("Brisbane", "Australia"),
  ("Riyadh", "Saudi Arabia"),
  ("Manila", "Philippines"),
  ("Cape Town", "South Africa"),
  ("Jakarta", "Indonesia"),
  ("Kolkata", "India"),
  ("Guangzhou", "China"),
  ("Abu Dhabi", "United Arab Emirates"),
  ("Casablanca", "Morocco"),
  ("Hanoi", "Vietnam"),
  ("Caracas", "Venezuela"),
  ("Tehran", "Iran"),
  ("Bucharest", "Romania"),
  ("Ljubljana", "Slovenia"),
  ("Havana", "Cuba"),
  ("Nicosia", "Cyprus"),
  ("Helsinki", "Finland"),
  ("Wellington", "New Zealand"),
  ("Ankara", "Turkey"),
  ("Bratislava", "Slovakia"),
  ("Bangalore", "India"),
  ("Krakow", "Poland"),
  ("Bogotá", "Colombia"),
  ("Tbilisi", "Georgia"),
  ("Colombo", "Sri Lanka"),
  ("San Juan", "Puerto Rico"),
  ("Windhoek", "Namibia"),
  ("Belgrade", "Serbia"),
  ("Manama", "Bahrain"),
  ("Baku", "Azerbaijan"),
  ("Tallinn", "Estonia"),
  ("Nairobi", "Kenya"),
  ("Islamabad", "Pakistan"),
  ("Kiev", "Ukraine"),
  ("Accra", "Ghana"),
  ("Lima", "Peru"),
  ("Copenhagen", "Denmark"),
  ("Tunis", "Tunisia"),
  ("Santiago", "Chile"),
  ("Doha", "Qatar"),
  ("Manila", "Philippines"),
  ("Riga", "Latvia")
]

NAME_COMPANIES_SECTORS = [
  ("Acme Technologies", "Technology"),
  ("Global Innovations Inc.", "Technology"),
  ("Strategic Solutions Co.", "Consulting"),
  ("Pinnacle Enterprises Ltd.", "Finance"),
  ("Creative Minds Agency", "Marketing"),
  ("EcoTech Solutions", "Environmental"),
  ("Infinite Insights Group", "Analytics"),
  ("Harmony Health Systems", "Healthcare"),
  ("Precision Manufacturing Inc.", "Manufacturing"),
  ("SynthCorp Labs", "Biotechnology"),
  ("Apex Financial Services", "Finance"),
  ("BlueSky Media Productions", "Media"),
  ("Quantum Technologies", "Technology"),
  ("FutureGen Innovations", "Innovation"),
  ("Vanguard Logistics", "Logistics"),
  ("United Energy Solutions", "Energy"),
  ("Agile Solutions Group", "Consulting"),
  ("TechVision Robotics", "Technology"),
  ("Pristine Pharmaceuticals", "Healthcare"),
  ("Global Dynamics Co.", "Consulting"),
  ("VentureX Capital", "Finance"),
  ("Tech Innovators Inc.", "Technology"),
  ("InnoVateTech Solutions", "Technology"),
  ("GreenScape Eco Solutions", "Environmental"),
  ("ConnectGlobal Telecommunications", "Telecommunications"),
  ("DataDriven Dynamics", "Data Science"),
  ("Maximus Security Systems", "Security"),
  ("HealthTech Solutions", "Healthcare"),
  ("Financial Dynamics Ltd.", "Finance"),
  ("Innovate Insights Consulting", "Consulting"),
  ("Apex Manufacturing Group", "Manufacturing"),
  ("TechSphere Solutions", "Technology"),
  ("Innovate Marketing Strategies", "Marketing"),
  ("SynthWave Technologies", "Technology"),
  ("Precision Pharma Solutions", "Healthcare"),
  ("Agile Analytics Co.", "Analytics"),
  ("Quantum Innovations Inc.", "Innovation"),
  ("GlobalLogix Logistics", "Logistics"),
  ("Pinnacle Energy Solutions", "Energy"),
  ("BlueSky Digital Media", "Media"),
  ("ConnectX Telecommunications", "Telecommunications"),
  ("United Manufacturing Systems", "Manufacturing"),
  ("FutureGen Biotech", "Biotechnology"),
  ("DataQuest Analytics", "Data Science"),
  ("HealthPrime Solutions", "Healthcare"),
  ("Infinite Insights Consulting", "Consulting"),
  ("GreenTech Innovations", "Environmental"),
  ("MaxSecure Security Systems", "Security"),
  ("TechNex Robotics", "Technology"),
  ("VentureX Financial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTech Manufacturing", "Manufacturing"),
  ("SynthSoft Software Solutions", "Technology"),
  ("EcoInnovate Environmental Solutions", "Environmental"),
  ("MediaMasters Productions", "Media"),
  ("ConnectSphere Telecommunications", "Telecommunications"),
  ("FutureWave Innovations", "Innovation"),
  ("GlobalPharma Health Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergy Solutions", "Technology"),
  ("Quantum Dynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobal Media", "Media"),
  ("DataDriven Security Systems", "Security"),
  ("HealthTech Innovations", "Healthcare"),
  ("Financial Insights Ltd.", "Finance"),
  ("InnovateConsult Consulting", "Consulting"),
  ("ApexManufacture Group", "Manufacturing"),
  ("TechVortex Solutions", "Technology"),
  ("InnoMark Marketing Strategies", "Marketing"),
  ("SynthWaveTech Technologies", "Technology"),
  ("PrecisionPharma Solutions", "Healthcare"),
  ("AgileData Analytics Co.", "Analytics"),
  ("QuantumInnovations Inc.", "Innovation"),
  ("GlobalLogistics Ltd.", "Logistics"),
  ("PinnacleEnergy Solutions", "Energy"),
  ("BlueSkyDigital Media", "Media"),
  ("ConnectXTelecom Telecommunications", "Telecommunications"),
  ("UnitedManufacture Systems", "Manufacturing"),
  ("FutureGenBiotech", "Biotechnology"),
  ("DataQuestAnalytics", "Data Science"),
  ("HealthPrimeSolutions", "Healthcare"),
  ("InfiniteInsights Consulting", "Consulting"),
  ("GreenTechInnovations", "Environmental"),
  ("MaxSecureSecurity Systems", "Security"),
  ("TechNexRobotics", "Technology"),
  ("VentureXFinancial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTechManufacturing", "Manufacturing"),
  ("SynthSoftSoftware Solutions", "Technology"),
  ("EcoInnovateEnvironmental Solutions", "Environmental"),
  ("MediaMastersProductions", "Media"),
  ("ConnectSphereTelecommunications", "Telecommunications"),
  ("FutureWaveInnovations", "Innovation"),
  ("GlobalPharmaHealth Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergySolutions", "Technology"),
  ("QuantumDynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobalMedia", "Media"),
  ("DataDrivenSecurity Systems", "Security"),
  ("HealthTechInnovations", "Healthcare"),
  ("FinancialInsights Ltd.", "Finance"),
  ("InnovateConsult Consulting", "Consulting"),
  ("ApexManufacture Group", "Manufacturing"),
  ("TechVortex Solutions", "Technology"),
  ("InnoMarkMarketing Strategies", "Marketing"),
  ("SynthWaveTech Technologies", "Technology"),
  ("PrecisionPharma Solutions", "Healthcare"),
  ("AgileData Analytics Co.", "Analytics"),
  ("QuantumInnovations Inc.", "Innovation"),
  ("GlobalLogistics Ltd.", "Logistics"),
  ("PinnacleEnergy Solutions", "Energy"),
  ("BlueSkyDigital Media", "Media"),
  ("ConnectXTelecom Telecommunications", "Telecommunications"),
  ("UnitedManufacture Systems", "Manufacturing"),
  ("FutureGenBiotech", "Biotechnology"),
  ("DataQuestAnalytics", "Data Science"),
  ("HealthPrimeSolutions", "Healthcare"),
  ("InfiniteInsights Consulting", "Consulting"),
  ("GreenTechInnovations", "Environmental"),
  ("MaxSecureSecurity Systems", "Security"),
  ("TechNexRobotics", "Technology"),
  ("VentureXFinancial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTechManufacturing", "Manufacturing"),
  ("SynthSoftSoftware Solutions", "Technology"),
  ("EcoInnovateEnvironmental Solutions", "Environmental"),
  ("MediaMastersProductions", "Media"),
  ("ConnectSphereTelecommunications", "Telecommunications"),
  ("FutureWaveInnovations", "Innovation"),
  ("GlobalPharmaHealth Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergySolutions", "Technology"),
  ("QuantumDynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobalMedia", "Media"),
  ("DataDrivenSecurity Systems", "Security"),
  ("HealthTechInnovations", "Healthcare"),
  ("FinancialInsights Ltd.", "Finance"),
  ("InnovateConsult Consulting", "Consulting"),
  ("ApexManufacture Group", "Manufacturing"),
  ("TechVortex Solutions", "Technology"),
  ("InnoMarkMarketing Strategies", "Marketing"),
  ("SynthWaveTech Technologies", "Technology"),
  ("PrecisionPharma Solutions", "Healthcare"),
  ("AgileData Analytics Co.", "Analytics"),
  ("QuantumInnovations Inc.", "Innovation"),
  ("GlobalLogistics Ltd.", "Logistics"),
  ("PinnacleEnergy Solutions", "Energy"),
  ("BlueSkyDigital Media", "Media"),
  ("ConnectXTelecom Telecommunications", "Telecommunications"),
  ("UnitedManufacture Systems", "Manufacturing"),
  ("FutureGenBiotech", "Biotechnology"),
  ("DataQuestAnalytics", "Data Science"),
  ("HealthPrimeSolutions", "Healthcare"),
  ("InfiniteInsights Consulting", "Consulting"),
  ("GreenTechInnovations", "Environmental"),
  ("MaxSecureSecurity Systems", "Security"),
  ("TechNexRobotics", "Technology"),
  ("VentureXFinancial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTechManufacturing", "Manufacturing"),
  ("SynthSoftSoftware Solutions", "Technology"),
  ("EcoInnovateEnvironmental Solutions", "Environmental"),
  ("MediaMastersProductions", "Media"),
  ("ConnectSphereTelecommunications", "Telecommunications"),
  ("FutureWaveInnovations", "Innovation"),
  ("GlobalPharmaHealth Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergySolutions", "Technology"),
  ("QuantumDynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobalMedia", "Media"),
  ("DataDrivenSecurity Systems", "Security"),
  ("HealthTechInnovations", "Healthcare"),
  ("FinancialInsights Ltd.", "Finance"),
  ("InnovateConsult Consulting", "Consulting"),
  ("ApexManufacture Group", "Manufacturing"),
  ("TechVortex Solutions", "Technology"),
  ("InnoMarkMarketing Strategies", "Marketing"),
  ("SynthWaveTech Technologies", "Technology"),
  ("PrecisionPharma Solutions", "Healthcare"),
  ("AgileData Analytics Co.", "Analytics"),
  ("QuantumInnovations Inc.", "Innovation"),
  ("GlobalLogistics Ltd.", "Logistics"),
  ("PinnacleEnergy Solutions", "Energy"),
  ("BlueSkyDigital Media", "Media"),
  ("ConnectXTelecom Telecommunications", "Telecommunications"),
  ("UnitedManufacture Systems", "Manufacturing"),
  ("FutureGenBiotech", "Biotechnology"),
  ("DataQuestAnalytics", "Data Science"),
  ("HealthPrimeSolutions", "Healthcare"),
  ("InfiniteInsights Consulting", "Consulting"),
  ("GreenTechInnovations", "Environmental"),
  ("MaxSecureSecurity Systems", "Security"),
  ("TechNexRobotics", "Technology"),
  ("VentureXFinancial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTechManufacturing", "Manufacturing"),
  ("SynthSoftSoftware Solutions", "Technology"),
  ("EcoInnovateEnvironmental Solutions", "Environmental"),
  ("MediaMastersProductions", "Media"),
  ("ConnectSphereTelecommunications", "Telecommunications"),
  ("FutureWaveInnovations", "Innovation"),
  ("GlobalPharmaHealth Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergySolutions", "Technology"),
  ("QuantumDynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobalMedia", "Media"),
  ("DataDrivenSecurity Systems", "Security"),
  ("HealthTechInnovations", "Healthcare"),
  ("FinancialInsights Ltd.", "Finance"),
  ("InnovateConsult Consulting", "Consulting"),
  ("ApexManufacture Group", "Manufacturing"),
  ("TechVortex Solutions", "Technology"),
  ("InnoMarkMarketing Strategies", "Marketing"),
  ("SynthWaveTech Technologies", "Technology"),
  ("PrecisionPharma Solutions", "Healthcare"),
  ("AgileData Analytics Co.", "Analytics"),
  ("QuantumInnovations Inc.", "Innovation"),
  ("GlobalLogistics Ltd.", "Logistics"),
  ("PinnacleEnergy Solutions", "Energy"),
  ("BlueSkyDigital Media", "Media"),
  ("ConnectXTelecom Telecommunications", "Telecommunications"),
  ("UnitedManufacture Systems", "Manufacturing"),
  ("FutureGenBiotech", "Biotechnology"),
  ("DataQuestAnalytics", "Data Science"),
  ("HealthPrimeSolutions", "Healthcare"),
  ("InfiniteInsights Consulting", "Consulting"),
  ("GreenTechInnovations", "Environmental"),
  ("MaxSecureSecurity Systems", "Security"),
  ("TechNexRobotics", "Technology"),
  ("VentureXFinancial Services", "Finance"),
  ("InnovateHealth Pharmaceuticals", "Healthcare"),
  ("PrecisionTechManufacturing", "Manufacturing"),
  ("SynthSoftSoftware Solutions", "Technology"),
  ("EcoInnovateEnvironmental Solutions", "Environmental"),
  ("MediaMastersProductions", "Media"),
  ("ConnectSphereTelecommunications", "Telecommunications"),
  ("FutureWaveInnovations", "Innovation"),
  ("GlobalPharmaHealth Solutions", "Healthcare"),
  ("InfiniteAnalytics Group", "Analytics"),
  ("TechSynergySolutions", "Technology"),
  ("QuantumDynamics Co.", "Innovation"),
  ("PinnacleLogix Logistics", "Logistics"),
  ("BlueSkyEnergy Solutions", "Energy"),
  ("ConnectGlobalMedia", "Media"),
  ("DataDrivenSecurity Systems", "Security"),
  ("HealthTechInnovations", "Healthcare")
]


id2category = {i: category for i, category in enumerate(CATEGORY_MANSIONS)}
category2id = {category: i for i, category in enumerate(CATEGORY_MANSIONS)}

name2id = {name: i for i, name in enumerate(UNIQUE_NAMES)}
name2gender = {name: gender for name, gender in zip(UNIQUE_NAMES, GENDER_LABELS)}



DESCRIPTIONS = [
    "I go by {NAME} {SURNAME}, occupying the {MANSION} of a {ADJECTIVE} {OCCUPATION}. With an {ADJECTIVE} zeal for {SPECIFIC_SKILL_OR_FIELD}, I carry {NUMBER} years of expertise into the {INDUSTRY} sector. Acclaimed for my {ADJECTIVE} {SKILLSET}, I excel in {TASK_OR_RESPONSIBILITY}, consistently delivering {QUALITY_OR_RESULT}. In my {OCCUPATION} role, I've showcased a {ADJECTIVE} mastery of {KEY_ACTION_OR_SKILL}, earning accolades for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues frequently praise my {ADJECTIVE} approach to {WORK_ACTIVITY}, recognizing my {ADJECTIVE} attention to detail and unwavering commitment to {WORK_VALUE}. I thrive in dynamic settings, seamlessly adapting to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills facilitate team collaboration, nurturing a {ADJECTIVE} work culture. Beyond my professional pursuits, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, underscoring my {ADJECTIVE} dedication to continuous growth and learning. Excited to bring my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and contribute to its {MISSION_OR_GOAL}.",
    "Presenting myself as {NAME} {SURNAME}, I hold the {MANSION} of a {ADJECTIVE} {OCCUPATION}. With an {ADJECTIVE} passion for {SPECIFIC_SKILL_OR_FIELD}, I bring {NUMBER} years of seasoned experience to the {INDUSTRY} domain. Acknowledged for my {ADJECTIVE} {SKILLSET}, I thrive in {TASK_OR_RESPONSIBILITY}, consistently yielding {QUALITY_OR_RESULT}. In my capacity as a {OCCUPATION}, I've demonstrated a {ADJECTIVE} proficiency in {KEY_ACTION_OR_SKILL}, earning recognition for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues often highlight my {ADJECTIVE} approach to {WORK_ACTIVITY}, citing my {ADJECTIVE} attention to detail and steadfast commitment to {WORK_VALUE}. I flourish in dynamic landscapes, seamlessly adapting to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills ease collaboration, fostering a {ADJECTIVE} work culture. Beyond my professional pursuits, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, spotlighting my {ADJECTIVE} dedication to continuous growth and learning. Enthusiastic about infusing my {ADJECTIVE} expertise into {COMPANY_NAME_OR_PROJECT} and contributing to its {MISSION_OR_GOAL}.",
    "A {MANSION} known by the name {NAME} {SURNAME}, I am immersed in the {INDUSTRY} industry as a {ADJECTIVE} {OCCUPATION}. Bringing {NUMBER} years of experience, my {ADJECTIVE} passion for {SPECIFIC_SKILL_OR_FIELD} is evident in my dedication. My {ADJECTIVE} {SKILLSET} ensures excellence in {TASK_OR_RESPONSIBILITY}, consistently delivering {QUALITY_OR_RESULT}. In the role of {OCCUPATION}, my {ADJECTIVE} ability to {KEY_ACTION_OR_SKILL} has earned accolades, and my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT} stands as a testament. Colleagues appreciate my {ADJECTIVE} approach to {WORK_ACTIVITY}, acknowledging my {ADJECTIVE} attention to detail and unwavering commitment to {WORK_VALUE}. Thriving in dynamic environments, I seamlessly adapt to {INDUSTRY_TRENDS} and embrace {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills foster collaboration, cultivating a {ADJECTIVE} work culture. Beyond my professional endeavors, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, showcasing my {ADJECTIVE} dedication to continuous growth and learning. Eager to bring my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and contribute to its {MISSION_OR_GOAL}.",
    "{NAME} {SURNAME}, residing in the {MANSION} of {OCCUPATION}, introduces a {ADJECTIVE} professional in the {INDUSTRY} industry. With {NUMBER} years of experience, my {ADJECTIVE} passion for {SPECIFIC_SKILL_OR_FIELD} propels me to excellence. The {ADJECTIVE} {SKILLSET} I possess ensures proficiency in {TASK_OR_RESPONSIBILITY}, consistently delivering {QUALITY_OR_RESULT}. In the capacity of {OCCUPATION}, I've showcased a {ADJECTIVE} mastery of {KEY_ACTION_OR_SKILL}, garnering acclaim for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues appreciate my {ADJECTIVE} approach to {WORK_ACTIVITY}, recognizing my {ADJECTIVE} attention to detail and steadfast commitment to {WORK_VALUE}. Adapting seamlessly to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}, I thrive in dynamic environments. My {ADJECTIVE} communication skills play a crucial role in fostering collaboration, contributing to a {ADJECTIVE} work culture. Beyond my professional pursuits, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, underscoring my {ADJECTIVE} dedication to continuous growth and learning. I am enthusiastic about contributing my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and supporting its {MISSION_OR_GOAL}.",
    "I am {NAME} {SURNAME}, a {MANSION} {ADJECTIVE} {OCCUPATION}. With a {ADJECTIVE} passion for {SPECIFIC_SKILL_OR_FIELD}, I bring {NUMBER} years of experience to the {INDUSTRY} industry. Known for my {ADJECTIVE} {SKILLSET}, I excel in {TASK_OR_RESPONSIBILITY} and consistently deliver {QUALITY_OR_RESULT}. In my role as a {OCCUPATION}, I've demonstrated a {ADJECTIVE} ability to {KEY_ACTION_OR_SKILL}, earning accolades for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues often commend my {ADJECTIVE} approach to {WORK_ACTIVITY}, noting my {ADJECTIVE} attention to detail and commitment to {WORK_VALUE}. I thrive in dynamic environments, adapting seamlessly to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills facilitate collaboration across teams, fostering a {ADJECTIVE} work culture. Beyond my professional endeavors, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, showcasing my {ADJECTIVE} dedication to continuous growth and learning. I am eager to bring my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and contribute to its {MISSION_OR_GOAL}.",
    "I am {NAME} {SURNAME}, a {MANSION} {ADJECTIVE} {OCCUPATION}. With an {ADJECTIVE} enthusiasm for {SPECIFIC_SKILL_OR_FIELD}, I bring {NUMBER} years of experience to the {INDUSTRY} sector. Acknowledged for my {ADJECTIVE} {SKILLSET}, I excel in {TASK_OR_RESPONSIBILITY} and consistently deliver {QUALITY_OR_RESULT}. In my capacity as a {OCCUPATION}, I've showcased a {ADJECTIVE} proficiency in {KEY_ACTION_OR_SKILL}, earning recognition for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues often applaud my {ADJECTIVE} approach to {WORK_ACTIVITY}, highlighting my {ADJECTIVE} attention to detail and dedication to {WORK_VALUE}. I thrive in dynamic environments, seamlessly adapting to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills facilitate collaboration across teams, fostering a {ADJECTIVE} work culture. Beyond my professional pursuits, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, underscoring my {ADJECTIVE} commitment to continuous growth and learning. I am enthusiastic about bringing my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and contributing to its {MISSION_OR_GOAL}.",
    "I am {NAME} {SURNAME}, a {MANSION} {ADJECTIVE} {OCCUPATION}. With a {ADJECTIVE} fervor for {SPECIFIC_SKILL_OR_FIELD}, I bring {NUMBER} years of experience to the {INDUSTRY} domain. Recognized for my {ADJECTIVE} {SKILLSET}, I excel in {TASK_OR_RESPONSIBILITY} and consistently deliver {QUALITY_OR_RESULT}.",
    "In my role as a {OCCUPATION}, I've demonstrated a {ADJECTIVE} proficiency in {KEY_ACTION_OR_SKILL}, earning accolades for my {ADJECTIVE} {PROJECT_OR_ACHIEVEMENT}. Colleagues often commend my {ADJECTIVE} approach to {WORK_ACTIVITY}, pointing out my {ADJECTIVE} attention to detail and commitment to {WORK_VALUE}. I thrive in dynamic environments, seamlessly adapting to {INDUSTRY_TRENDS} and embracing {TECHNOLOGICAL_ADVANCEMENTS}. My {ADJECTIVE} communication skills facilitate collaboration across teams, cultivating a {ADJECTIVE} work culture. Beyond my professional pursuits, I am {ADJECTIVE} in {HOBBY_OR_INTEREST}, showcasing my {ADJECTIVE} dedication to continuous growth and learning. I am eager to bring my {ADJECTIVE} expertise to {COMPANY_NAME_OR_PROJECT} and contribute to its {MISSION_OR_GOAL}."
]


SLOT_VALUES = {
  "{ADJECTIVE}": ["dedicated", "innovative", "meticulous", "adaptive", "proactive", "dynamic", "resourceful", "tenacious", "versatile", "creative"],
  "{OCCUPATION}": ["software developer", "marketing specialist", "financial analyst", "project manager", "graphic designer", "data scientist", "customer success manager", "UX/UI designer", "social media strategist", "cybersecurity analyst"],
  "{SPECIFIC_SKILL_OR_FIELD}": ["web development", "data analysis", "content creation", "strategic planning", "user interface design", "mobile app development", "market research", "financial modeling", "project management", "branding"],
  "{NUMBER}": ["5", "10", "15", "20", "25", "8", "12", "18", "22", "30"],
  "{INDUSTRY}": ["technology", "healthcare", "finance", "entertainment", "manufacturing", "education", "retail", "energy", "hospitality", "telecommunications"],
  "{SKILLSET}": ["strong analytical skills", "effective communication", "leadership abilities", "creative problem-solving", "collaborative teamwork", "strategic thinking", "data visualization", "negotiation skills", "project coordination", "innovative thinking"],
  "{TASK_OR_RESPONSIBILITY}": ["managing cross-functional teams", "developing and implementing marketing strategies", "conducting financial analysis", "leading software development projects", "designing visually appealing graphics", "optimizing SEO strategies", "analyzing market trends", "budget planning and forecasting", "risk management", "creating engaging social media content"],
  "{QUALITY_OR_RESULT}": ["high-quality deliverables", "measurable results", "improved efficiency", "innovative solutions", "positive outcomes", "customer satisfaction", "cost savings", "strategic growth", "increased market share", "effective risk mitigation"],
  "{PROJECT_OR_ACHIEVEMENT}": ["successful product launch", "increased customer engagement", "cost-effective process improvement", "awarded for excellence", "implemented successful marketing campaign", "achieved ISO certification", "streamlined supply chain", "developed patent-pending technology", "secured major partnerships", "launched sustainable initiatives"],
  "{WORK_ACTIVITY}": ["coding", "researching market trends", "budget planning", "team collaboration", "creative design", "conducting user interviews", "analyzing big data sets", "strategic planning sessions", "agile development", "multimedia content creation"],
  "{WORK_VALUE}": ["integrity", "excellence", "teamwork", "innovation", "customer satisfaction", "sustainability", "diversity and inclusion", "ethical business practices", "continuous learning", "social responsibility"],
  "{INDUSTRY_TRENDS}": ["emerging technologies", "sustainability practices", "digital transformation", "remote work trends", "customer-centric approaches", "blockchain integration", "AI-driven innovations", "cybersecurity advancements", "virtual events", "personalized user experiences"],
  "{TECHNOLOGICAL_ADVANCEMENTS}": ["AI and machine learning", "blockchain technology", "cloud computing", "automation", "virtual reality", "edge computing", "biotechnology", "quantum computing", "robotic process automation", "smart cities technology"],
  "{COMPANY_NAME_OR_PROJECT}": ["Tech Innovators Inc.", "HealthTech Solutions", "Financial Dynamics Ltd.", "Creative Minds Agency", "Manufactura Enterprises", "GreenTech Innovations", "FutureGen Solutions", "InnoVateTech", "DataDriven Dynamics", "GlobalImpact Ventures"],
  "{MISSION_OR_GOAL}": ["transforming industries through innovation", "improving healthcare accessibility", "providing financial empowerment", "inspiring creativity through design", "revolutionizing manufacturing processes", "advancing environmental sustainability", "empowering global communities", "facilitating inclusive education", "driving social impact", "building a more connected world"]
}
